language: python
sudo: enabled
cache:
  directories:
  - $HOME/.cache/pip
  - /tmp/cached/
python:
- '3.5'
- '3.6'
install:
- make init
script:
- make test
jobs:
  include:
  - stage: test
    name: "Check Black Formatting"
    python: 3.6
    script: make check-formatting
